#!/bin/bash
# ---------------------------------------------------------------------------
# Rahyaft Sanat — container bootstrap.
#
# Brings a bare container up to a running, installed site without the operator
# touching install.php: it waits for MariaDB, writes the container's .env,
# loads database/schema.sql on first run, imports database/content/ and creates
# the development administrator. Every step is idempotent, so restarting the
# container is safe and fast.
# ---------------------------------------------------------------------------
set -euo pipefail

ROOT=/var/www/html
ENV_FILE="$ROOT/.env"
LOCK_FILE="$ROOT/installed.lock"

log() { printf '  \033[36m→\033[0m %s\n' "$*"; }
ok()  { printf '  \033[32m✓\033[0m %s\n' "$*"; }
bad() { printf '  \033[31m✗\033[0m %s\n' "$*" >&2; }

: "${DB_HOST:=db}"
: "${DB_PORT:=3306}"
: "${DB_NAME:=rahyaft}"
: "${DB_USER:=rahyaft_user}"
: "${DB_PASSWORD:=rahyaft}"
: "${APP_URL:=http://localhost:8100}"
: "${APP_ENV:=local}"
: "${APP_DEBUG:=true}"
: "${ADMIN_NAME:=Local Admin}"
: "${ADMIN_EMAIL:=admin@localhost}"
: "${ADMIN_PASSWORD:=password1234}"
: "${MAIL_MAILER:=smtp}"
: "${MAIL_HOST:=mailpit}"
: "${MAIL_PORT:=1025}"
: "${MAIL_ENCRYPTION:=}"
: "${MAIL_FROM_ADDRESS:=no-reply@rahyaft.test}"
: "${MAIL_FROM_NAME:=Rahyaft Sanat}"
: "${MAIL_NOTIFY_TO:=}"

printf '\n\033[1mRahyaft Sanat — container bootstrap\033[0m\n'

# --- 1. Match www-data to the owner of the bind mount -----------------------
# On Linux hosts the project files are owned by the developer's UID; Apache
# must share it or uploads and logs fail. On Docker Desktop this is a no-op.
host_uid="$(stat -c '%u' "$ROOT")"
host_gid="$(stat -c '%g' "$ROOT")"
if [ "$host_uid" != "0" ] && [ "$host_uid" != "$(id -u www-data)" ]; then
    groupmod -o -g "$host_gid" www-data 2>/dev/null || true
    usermod  -o -u "$host_uid" -g "$host_gid" www-data 2>/dev/null || true
    log "Mapped www-data to uid $host_uid:$host_gid (host owner)"
fi

# --- 2. Runtime directories -------------------------------------------------
mkdir -p "$ROOT/storage/logs" "$ROOT/storage/cache" \
         "$ROOT/uploads/files" "$ROOT/uploads/thumbs" "$ROOT/uploads/media"
chown -R www-data:www-data "$ROOT/storage" "$ROOT/uploads" 2>/dev/null || true
chmod -R u+rwX "$ROOT/storage" "$ROOT/uploads" 2>/dev/null || true

# --- 3. Wait for MariaDB ----------------------------------------------------
mysql_bin=mariadb
command -v mariadb >/dev/null 2>&1 || mysql_bin=mysql

# The MariaDB client warns about server-certificate verification on every
# invocation; the connection never leaves the compose network, so silence it.
mysql_flags=()
if [ "$mysql_bin" = mariadb ]; then
    mysql_flags=(--disable-ssl-verify-server-cert)
fi

log "Waiting for MariaDB at $DB_HOST:$DB_PORT …"
for i in $(seq 1 90); do
    if MYSQL_PWD="$DB_PASSWORD" "$mysql_bin" "${mysql_flags[@]}" \
        -h "$DB_HOST" -P "$DB_PORT" -u "$DB_USER" -D "$DB_NAME" \
        -e 'SELECT 1' >/dev/null 2>&1; then
        ok "Database reachable ($DB_NAME@$DB_HOST)"
        break
    fi
    if [ "$i" = 90 ]; then
        bad "MariaDB did not become reachable in 90s"
        exit 1
    fi
    sleep 1
done

db_query() {
    MYSQL_PWD="$DB_PASSWORD" "$mysql_bin" "${mysql_flags[@]}" \
        -h "$DB_HOST" -P "$DB_PORT" -u "$DB_USER" -D "$DB_NAME" -N -B -e "$1"
}

as_web() { su -s /bin/bash www-data -c "cd $ROOT && $1"; }

# --- 4. The container's .env ------------------------------------------------
# Bind-mounted from docker/state/app.env, so the developer's own .env on the
# host is never touched. APP_KEY is generated once and then preserved.
app_key=""
if [ -f "$ENV_FILE" ]; then
    app_key="$(sed -n 's/^APP_KEY=//p' "$ENV_FILE" | head -1 | tr -d '"'"'"'')"
fi
if [ -z "$app_key" ]; then
    app_key="$(php -r 'echo bin2hex(random_bytes(24));')"
    log "Generated a new APP_KEY"
fi

cat > "$ENV_FILE" <<EOF
# Generated by the Docker entrypoint on every start — edit docker-compose.yml
# (the app service's environment) rather than this file.
APP_ENV=$APP_ENV
APP_DEBUG=$APP_DEBUG
APP_URL=$APP_URL
APP_KEY=$app_key
APP_DEFAULT_LOCALE=${APP_DEFAULT_LOCALE:-fa}
APP_LOCALES=${APP_LOCALES:-fa,en,ar}

DB_HOST=$DB_HOST
DB_PORT=$DB_PORT
DB_NAME=$DB_NAME
DB_USER=$DB_USER
DB_PASSWORD=$DB_PASSWORD
DB_CHARSET=utf8mb4

MAIL_MAILER=$MAIL_MAILER
MAIL_HOST=$MAIL_HOST
MAIL_PORT=$MAIL_PORT
MAIL_ENCRYPTION=$MAIL_ENCRYPTION
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_FROM_ADDRESS=$MAIL_FROM_ADDRESS
MAIL_FROM_NAME="$MAIL_FROM_NAME"
MAIL_NOTIFY_TO=$MAIL_NOTIFY_TO
EOF
chown www-data:www-data "$ENV_FILE" 2>/dev/null || true
chmod 600 "$ENV_FILE" 2>/dev/null || true
ok "Wrote .env (container configuration)"

# --- 5. Schema --------------------------------------------------------------
table_count="$(db_query "SELECT COUNT(*) FROM information_schema.tables
                         WHERE table_schema = '$DB_NAME';" 2>/dev/null || echo 0)"

if [ "${table_count:-0}" -lt 1 ]; then
    log "Empty database — loading database/schema.sql"
    MYSQL_PWD="$DB_PASSWORD" "$mysql_bin" "${mysql_flags[@]}" \
        -h "$DB_HOST" -P "$DB_PORT" -u "$DB_USER" -D "$DB_NAME" \
        < "$ROOT/database/schema.sql"
    ok "Schema loaded ($(grep -c 'CREATE TABLE' "$ROOT/database/schema.sql") tables)"
else
    ok "Schema present ($table_count tables)"
fi

# --- 6. Content -------------------------------------------------------------
# The seeder keys on slugs and is safe to re-run, but re-importing on every
# restart would discard editor changes, so it only runs while the site is empty.
product_count="$(db_query 'SELECT COUNT(*) FROM products;' 2>/dev/null || echo 0)"

if [ "${product_count:-0}" -lt 1 ] || [ "${SEED_ON_START:-0}" = "1" ]; then
    log "Importing content from database/content/"
    as_web "php database/seed.php" | sed 's/^/    /'
else
    ok "Content present ($product_count products)"
fi

# --- 7. Administrator -------------------------------------------------------
admin_state="$(as_web "php -r '
    require \"app/Core/Autoloader.php\";
    App\\Core\\Autoloader::register(__DIR__);
    require \"app/Support/helpers.php\";
    App\\Core\\Env::load(__DIR__ . \"/.env\");
    App\\Core\\Config::loadDirectory(__DIR__ . \"/config\");
    App\\Core\\Config::set(\"app.base_path\", __DIR__);
    if (App\\Models\\AdminUser::emailExists(\"$ADMIN_EMAIL\")) {
        echo \"already present\";
    } else {
        App\\Models\\AdminUser::create(\"$ADMIN_NAME\", \"$ADMIN_EMAIL\", \"$ADMIN_PASSWORD\", \"owner\");
        echo \"created\";
    }
'")"
ok "Administrator $ADMIN_EMAIL (${admin_state:-unknown})"

# --- 8. Installation lock ---------------------------------------------------
if [ ! -s "$LOCK_FILE" ]; then
    printf 'installed %s\n' "$(date -u +%FT%TZ)" > "$LOCK_FILE"
    ok "Installation locked"
fi
chown www-data:www-data "$LOCK_FILE" 2>/dev/null || true
chmod 600 "$LOCK_FILE" 2>/dev/null || true

printf '\n  \033[1mSite\033[0m     %s\n' "$APP_URL"
printf '  \033[1mAdmin\033[0m    %s/admin  —  %s / %s\n\n' "$APP_URL" "$ADMIN_EMAIL" "$ADMIN_PASSWORD"

exec "$@"
